
name: "Test ROS2 actions"
on:
  schedule:
    # Run the CI automatically nighly.
    - cron:  '0 * * * *'
  push:
      
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [master]
          os: [ubuntu-18.04]
    steps:
    #- name: Acquire ROS dependencies
    #  uses: ros-tooling/setup-ros@0.0.17
      
    #- name: Build and test ROS
    #  uses: ros-tooling/action-ros-ci@0.0.15
    #  with:
    #    package-name: rmw_cyclonedds_cpp
    #    vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/${{ matrix.rosdistro }}/ros2.repos


   # - name: Checkout
   #   uses: actions/checkout@master
   #   with:
   #       repository: irobot-ros/ros2-performance
   #       working-directory: ./ros2-performance

    - name: build test
      run: bash .github/workflows/build-test.sh
