
name: "Test ROS2 actions"
on:
  # schedule:
    # Run the CI automatically nighly.
    # - cron:  '0 0 * * *'
  push:
      
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@0.0.17

    - name: Checkout
      uses: actions/checkout@master

    - name: Run script
      run: bash .github/workflows/build-test.sh
